service: IotaProxy
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2

functions:
  attHandler:
    handler: AttHandler.handler
    #5 mins, hopefully enough for PoW
    timeout: 300